### ISSUE TITLE
Does not take `compilation.children` into account

### ISSUE THREAD

**Issue by EECOLOR** [GProst/webpack-clean-obsolete-chunks#21]
Compilations can have child compilations with separate chunks. It would be great if this plugin would take those children into account as well.

The Stats class does show the children: https://github.com/webpack/webpack/blob/v3.5.5/lib/Stats.js#L412

**Comment by GProst** [comment]
Hi @EECOLOR!
Can you please help me by explaining how can I reproduce this case so I could test it?

You create child compiler via webpack Node.js API and it then emits separate chunks?

**Comment by GProst** [comment]
Thank you!
Will do this within this week.

**Comment by GProst** [comment]
Just want to warn that it looks like this will work correctly only if all descendant-compilations of the initial compilation have **unique** names. Because I can't see another way to distinguish one from another. Each compilation has its own chunks id list order, so I can't combine all chunks in one list (there will be collisions). I will check chunks separately for each compilation.

**Comment by GProst** [comment]
Done.
Provide `{deep: true}` option to plugin constructor.

**Comment by EECOLOR** [comment]
@GProst great work!

> Just want to warn that it looks like this will work correctly only if all descendant-compilations of the initial compilation have unique names.

That is fine. In all examples I've seen the child compiler has a distinct name and this name is copied to the compilation.
